DockerHub Image Documentation
CDOT-CV/jpo-s3-deposit pull request #10
Opened 2023-11-10 18:51 UTC by dmccoystephenson

## Changes
Documentation for using the image has been added to `docs/dockerhub.md`.

2023-11-22 23:59 UTC, drewjj approved these changes
This looks good to me.

2024-01-17 00:09 UTC, payneBrandon commented on docs/dockerhub.md
> +The purpose of the jpo-s3-deposit program is to deposit messages to an Amazon S3 bucket or some other destination.
Maybe tweak a bit to something like:
`
The purpose of the jpo-s3-deposit program is to deposit messages to permanent storage, such as an Amazon S3 bucket, mongodb instance, or other similar system.
`

2024-01-17 00:09 UTC, payneBrandon requested changes
Just the one comment

2024-01-25 16:28 UTC, payneBrandon approved these changes
lgtm!

2024-01-25 16:28 UTC, merged